<a href="https://colab.research.google.com/github/MohammedShahad7/Data-Science-/blob/main/Cleaning_a_Raw_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import io

csv_data = """ Order ID , Region ,Category , Sales , Quantity , Order Date
1001 , north , Electronics , "$1,200" , 10 units , 01-01-2024
1002 , South, electronics , "$850" , 5 Units , 02-01-2024
1003 , EAST , Furniture , "$2,500" , 3 units , 03-01-2024
1004 , west , furnture , "$1,750" , 2 units , 04-01-2024
1005 , Noth , Electronics , "$1,200" , 10 units , 01-01-2024
1005 , Noth , Electronics , "$1,200" , 10 units , 01-01-2024
1006 , south , Office Supplies , "$300" , 7 units , 05-01-2024
1007 , East , office supplies , "$450" , 4 Units , 06-01-2024
1008 , WEST , Electronics , "$1,100" , 6 units , 07-01-2024
"""

df = pd.read_csv(io.StringIO(csv_data), skipinitialspace=True)

print(df.head())

   Order ID  Region      Category    Sales   Quantity   Order Date
0       1001  north   Electronics   $1,200   10 units   01-01-2024
1       1002   South  electronics     $850    5 Units   02-01-2024
2       1003   EAST     Furniture   $2,500    3 units   03-01-2024
3       1004   west      furnture   $1,750    2 units   04-01-2024
4       1005   Noth   Electronics   $1,200   10 units   01-01-2024

In [5]:
df.columns=df.columns.str.strip().str.title()
df.drop_duplicates()
print(df.head())

   Order Id  Region      Category    Sales   Quantity  Order Date
0      1001  north   Electronics   $1,200   10 units   01-01-2024
1      1002   South  electronics     $850    5 Units   02-01-2024
2      1003   EAST     Furniture   $2,500    3 units   03-01-2024
3      1004   west      furnture   $1,750    2 units   04-01-2024
4      1005   Noth   Electronics   $1,200   10 units   01-01-2024

In [6]:
df['Region']=df['Region'].str.strip()
df['Region']=df['Region'].str.title()
df['Region']=df['Region'].replace("Noth","North")

df.head()

   Order Id Region      Category    Sales   Quantity  Order Date
0      1001  North  Electronics   $1,200   10 units   01-01-2024
1      1002  South  electronics     $850    5 Units   02-01-2024
2      1003   East    Furniture   $2,500    3 units   03-01-2024
3      1004   West     furnture   $1,750    2 units   04-01-2024
4      1005  North  Electronics   $1,200   10 units   01-01-2024

In [7]:
df['Category']=df['Category'].str.strip().str.title()
df['Category']=df['Category'].replace("Furnture","Furniture")

df.head()

   Order Id Region     Category    Sales   Quantity  Order Date
0      1001  North  Electronics  $1,200   10 units   01-01-2024
1      1002  South  Electronics    $850    5 Units   02-01-2024
2      1003   East    Furniture  $2,500    3 units   03-01-2024
3      1004   West    Furniture  $1,750    2 units   04-01-2024
4      1005  North  Electronics  $1,200   10 units   01-01-2024

In [8]:
df['Sales']=df['Sales'].str.replace("$","",regex=False)
df['Sales']=df['Sales'].str.replace(",","",regex=False)
df['Sales']=df['Sales'].astype(float)

df.head()

   Order Id Region     Category   Sales   Quantity  Order Date
0      1001  North  Electronics  1200.0  10 units   01-01-2024
1      1002  South  Electronics   850.0   5 Units   02-01-2024
2      1003   East    Furniture  2500.0   3 units   03-01-2024
3      1004   West    Furniture  1750.0   2 units   04-01-2024
4      1005  North  Electronics  1200.0  10 units   01-01-2024

In [11]:
df['Quantity']=df['Quantity'].str.lower().str.replace("units","",regex=False).str.strip()


df['Quantity']=df['Quantity'].astype(int)

df.head()

   Order Id Region     Category   Sales  Quantity  Order Date
0      1001  North  Electronics  1200.0        10  01-01-2024
1      1002  South  Electronics   850.0         5  02-01-2024
2      1003   East    Furniture  2500.0         3  03-01-2024
3      1004   West    Furniture  1750.0         2  04-01-2024
4      1005  North  Electronics  1200.0        10  01-01-2024

In [14]:
df['Order Date']=pd.to_datetime(df['Order Date'])
df.head()

   Order Id Region     Category   Sales  Quantity Order Date
0      1001  North  Electronics  1200.0        10 2024-01-01
1      1002  South  Electronics   850.0         5 2024-02-01
2      1003   East    Furniture  2500.0         3 2024-03-01
3      1004   West    Furniture  1750.0         2 2024-04-01
4      1005  North  Electronics  1200.0        10 2024-01-01