<a href="https://colab.research.google.com/github/MohammedShahad7/Data-Science-/blob/main/Grouping%20and%20Comparing%20Data%20Segments.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import seaborn as sns
import numpy as np

In [3]:
df=sns.load_dataset('tips')

df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
df['Spending_Type']=np.where(df['total_bill']>20,"Premium","Budget")

In [12]:
df['tip_pct']=(df['tip']/df['total_bill']*100)

In [13]:
df[['Spending_Type','tip_pct']].head()

  Spending_Type    tip_pct
0        Budget   5.944673
1        Budget  16.054159
2       Premium  16.658734
3       Premium  13.978041
4       Premium  14.680765

In [23]:
summart = pd.pivot_table(
    df,
    values=['tip_pct','size'],
    index=['day','Spending_Type'],
    aggfunc={
        'tip_pct':'median',
        'size':'mean'
    }
)

print(summart.round(2))

                    size  tip_pct
day  Spending_Type
Thur Budget         2.04    15.88
     Premium        3.62    14.14
Fri  Budget         2.00    18.77
     Premium        2.33    14.28
Sat  Budget         2.22    15.66
     Premium        2.89    13.75
Sun  Budget         2.33    16.63
     Premium        3.38    14.68

/tmp/ipykernel_1108/3901167338.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  summart = pd.pivot_table(

In [20]:
sammer=df.groupby(['day','Spending_Type']).agg({
    'tip_pct':'median',
    'size':'mean'
}).round(2)

print(sammer)

                    tip_pct  size
day  Spending_Type
Thur Budget           15.88  2.04
     Premium          14.14  3.62
Fri  Budget           18.77  2.00
     Premium          14.28  2.33
Sat  Budget           15.66  2.22
     Premium          13.75  2.89
Sun  Budget           16.63  2.33
     Premium          14.68  3.38

/tmp/ipykernel_1108/1641058060.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sammer=df.groupby(['day','Spending_Type']).agg({

In [24]:
global_avg_tip = df['tip_pct'].mean()

global_avg_tip

np.float64(16.08025817225047)

In [25]:
avg_tip_by_type = df.groupby('Spending_Type')['tip_pct'].mean()

avg_tip_by_type

Spending_Type
Budget     17.357164
Premium    14.145153
Name: tip_pct, dtype: float64

In [26]:
delta=avg_tip_by_type['Budget']- avg_tip_by_type['Premium']

delta

np.float64(3.2120104921933805)