<a href="https://colab.research.google.com/github/MohammedShahad7/Data-Science-/blob/main/Handling_Missing_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

data = {
    'Customer_ID': [1, 2, 3, 4, 5, 6, 8, 9, 10],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan'],
    'Age': [25, np.nan, 30, 22, 45, np.nan, 33, 38, np.nan],
    'City': ['New York', 'London', np.nan, 'London', 'Paris', 'New York', 'London', np.nan, 'Paris'],
    'Spend_Amount': [150, 200, 120, np.nan, 300, 180, np.nan, 210, 190],
    'Feedback_Notes': [np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan]
}

df = pd.DataFrame(data)

df.head()

   Customer_ID     Name   Age      City  Spend_Amount  Feedback_Notes
0            1    Alice  25.0  New York         150.0             NaN
1            2      Bob   NaN    London         200.0             NaN
2            3  Charlie  30.0       NaN         120.0             NaN
3            4    David  22.0    London           NaN             NaN
4            5      Eve  45.0     Paris         300.0             NaN

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Customer_ID     9 non-null      int64
 1   Name            9 non-null      object
 2   Age             6 non-null      float64
 3   City            7 non-null      object
 4   Spend_Amount    7 non-null      float64
 5   Feedback_Notes  0 non-null      float64
dtypes: float64(3), int64(1), object(2)
memory usage: 564.0+ bytes

In [3]:
num_row=df.shape[0]
print("Number of Row: \n",num_row)
num_col=df.shape[1]
print("Number of Column: \n",num_col)

Number of Row:
 9
Number of Column:
 6

In [4]:
all_is_null = df.columns[df.isnull().all()][0]
print("Columns where all values are null:", all_is_null)

Columns where all values are null: Feedback_Notes

In [5]:
print("The `Notes` column should be dropped because it contains 100% missing values (all entries are null). Since it has no useful data, keeping it would only waste memory and add unnecessary complexity to the dataset.")
df.dropna(axis=1,how='all',inplace=True)
df.head()

The `Notes` column should be dropped because it contains 100% missing values (all entries are null). Since it has no useful data, keeping it would only waste memory and add unnecessary complexity to the dataset.

   Customer_ID     Name   Age      City  Spend_Amount
0            1    Alice  25.0  New York         150.0
1            2      Bob   NaN    London         200.0
2            3  Charlie  30.0       NaN         120.0
3            4    David  22.0    London           NaN
4            5      Eve  45.0     Paris         300.0

In [6]:
avg_Age=df['Age'].mean()
df['Age'].fillna(avg_Age,inplace=True)
df.head()

/tmp/ipykernel_7546/524748016.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(avg_Age,inplace=True)

   Customer_ID     Name        Age      City  Spend_Amount
0            1    Alice  25.000000  New York         150.0
1            2      Bob  32.166667    London         200.0
2            3  Charlie  30.000000       NaN         120.0
3            4    David  22.000000    London           NaN
4            5      Eve  45.000000     Paris         300.0

In [12]:
mode_City=df['City'].mode()[0]
df['City'].fillna(mode_City,inplace=True)
df.head()

/tmp/ipykernel_7546/2622702169.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['City'].fillna(mode_City,inplace=True)

   Customer_ID     Name        Age      City  Spend_Amount
0            1    Alice  25.000000  New York         150.0
1            2      Bob  32.166667    London         200.0
2            3  Charlie  30.000000  New York         120.0
4            5      Eve  45.000000     Paris         300.0
5            6    Frank  32.166667  New York         180.0

In [13]:
df.dropna(axis=0,subset=['Spend_Amount'],inplace=True)
df.head()

   Customer_ID     Name        Age      City  Spend_Amount
0            1    Alice  25.000000  New York         150.0
1            2      Bob  32.166667    London         200.0
2            3  Charlie  30.000000  New York         120.0
4            5      Eve  45.000000     Paris         300.0
5            6    Frank  32.166667  New York         180.0

In [14]:
df.isnull().sum()

Customer_ID     0
Name            0
Age             0
City            0
Spend_Amount    0
dtype: int64

In [16]:
df.shape

(7, 5)