<a href="https://colab.research.google.com/github/MohammedShahad7/Data-Science-/blob/main/Indexing_and_Filtering_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [6]:
URL="https://raw.githubusercontent.com/CodeVinayak/Student-Performance-Analysis-Machine-Learning/master/StudentsPerformance.csv"

df=pd.read_csv(URL)

df.head()

,gender,race,parental_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [7]:
scores_subset=df[['reading_score','math_score','gender']]

scores_subset.head()

   reading_score  math_score  gender
0             72          72  female
1             90          69  female
2             95          90  female
3             57          47    male
4             78          76    male

In [9]:
The_10_19=df.iloc[10:20]
print("The row 10 t0 19:\n",The_10_19)

The row 10 t0 19:
     gender     race  parental_education         lunch test_preparation_course  \
10    male  group C  associate's degree      standard                    none
11    male  group D  associate's degree      standard                    none
12  female  group B         high school      standard                    none
13    male  group A        some college      standard               completed
14  female  group A     master's degree      standard                    none
15  female  group C    some high school      standard                    none
16    male  group C         high school      standard                    none
17  female  group B    some high school  free/reduced                    none
18    male  group C     master's degree  free/reduced               completed
19  female  group C  associate's degree  free/reduced                    none

    math_score  reading_score  writing_score
10          58             54             52
11          40             52             43
12          65             81             73
13          78             72             70
14          50             53             58
15          69             75             78
16          88             89             86
17          18             32             28
18          46             42             46
19          54             58             61

In [12]:
only_MAth=df['math_score']
print("Math Score:\n",only_MAth)

Math Score:
 0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math_score, Length: 1000, dtype: int64

In [13]:
The_math_score_more_then_80=df[df['math_score']>80]
print("The math score more then 80:\n",The_math_score_more_then_80)

The math score more then 80:
      gender     race  parental_education         lunch  \
2    female  group B     master's degree      standard
6    female  group B        some college      standard
16     male  group C         high school      standard
34     male  group E        some college      standard
35     male  group E  associate's degree      standard
..      ...      ...                 ...           ...
979  female  group C  associate's degree      standard
981    male  group D    some high school      standard
987    male  group E    some high school      standard
990    male  group E         high school  free/reduced
995  female  group E     master's degree      standard

    test_preparation_course  math_score  reading_score  writing_score
2                      none          90             95             93
6                 completed          88             95             92
16                     none          88             89             86
34                     none          97             87             82
35                completed          81             81             79
..                      ...         ...            ...            ...
979                    none          91             95             94
981                    none          81             78             78
987               completed          81             75             76
990               completed          86             81             75
995               completed          88             99             95

[176 rows x 8 columns]

In [17]:
The_read_75__write_70=df[(df['reading_score']>75)&(df['writing_score']>70)]
print("The read score more then 75 & write score more then 70:\n 5 ROW: \n",The_read_75__write_70.head())

The read score more then 75 & write score more then 70:
 5 ROW:
    gender     race  parental_education     lunch test_preparation_course  \
1  female  group C        some college  standard               completed
2  female  group B     master's degree  standard                    none
4    male  group C        some college  standard                    none
5  female  group B  associate's degree  standard                    none
6  female  group B        some college  standard               completed

   math_score  reading_score  writing_score
1          69             90             88
2          90             95             93
4          76             78             75
5          71             83             78
6          88             95             92