<a href="https://colab.research.google.com/github/MohammedShahad7/Data-Science-/blob/main/Pandas_DataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
URL="https://raw.githubusercontent.com/CodeVinayak/Student-Performance-Analysis-Machine-Learning/master/StudentsPerformance.csv"

df=pd.read_csv(URL)

df.head()

,gender,race,parental_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [3]:
df.shape

(1000, 8)

In [4]:
df.columns

Index(['gender', 'race', 'parental_education', 'lunch',
       'test_preparation_course', 'math_score', 'reading_score',
       'writing_score'],
      dtype='object')

In [7]:
df.shape[0]

1000

In [8]:
df.shape[1]

8

In [9]:
df.dtypes

gender                     object
race                       object
parental_education         object
lunch                      object
test_preparation_course    object
math_score                  int64
reading_score               int64
writing_score               int64
dtype: object

In [10]:
numeric_columns = df.select_dtypes(include=['int64', 'float64']).columns

# Categorical columns
categorical_columns = df.select_dtypes(include=['object']).columns

# Print results
print("Numeric Columns:")
print(list(numeric_columns))

print("\nCategorical Columns:")
print(list(categorical_columns))

Numeric Columns:
['math_score', 'reading_score', 'writing_score']

Categorical Columns:
['gender', 'race', 'parental_education', 'lunch', 'test_preparation_course']

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   gender                   1000 non-null   object
 1   race                     1000 non-null   object
 2   parental_education       1000 non-null   object
 3   lunch                    1000 non-null   object
 4   test_preparation_course  1000 non-null   object
 5   math_score               1000 non-null   int64
 6   reading_score            1000 non-null   int64
 7   writing_score            1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [16]:
# Check missing values
if df.isnull().sum().sum() == 0:
    print("Are there any missing values? No")
else:
    print("Are there any missing values? Yes")

# Check memory usage
memory_usage = df.memory_usage(deep=True).sum() / 1024

print(f"Memory Usage: {memory_usage:.2f} KB")

Are there any missing values? No
Memory Usage: 303.71 KB