<a href="https://colab.research.google.com/github/MohammedShahad7/Data-Science-/blob/main/Structuring_and_Preparing_Data_for_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

# Raw data dictionary
data = {
    'Order_ID': [1001, 1002, 1003, 1004, 1005, 1005, 1006, 1007, 1008, 1009, 1010, 1011],
    ' Region ': ['north', 'South', 'EAST', 'west', 'North', 'North', 'south', 'East', 'WEST', 'north', 'South', 'east'],
    'Category': ['Electronics', 'electronics', 'Furniture', 'furnture', 'Electronics', 'Electronics', 'Office Supplies', 'office supplies', 'Electronics', 'Furniture', 'Electronics', 'Electronics'],
    'Sales': ['$1200', '$850', '$2500', '$1750', '$1200', '$1200', '$300', '$450', '$1100', np.nan, '$950', '$1300'],
    'Quantity': [5, 3, 2, 1, 5, 5, 7, 4, 6, 2, np.nan, 4],
    'Profit': [200, 120, 400, 250, 200, 200, 50, 60, 180, 90, 150, 220],
    'Order_Date': ['01-01-2024', '02-01-2024', '03-01-2024', '04-01-2024', '01-01-2024', '01-01-2024', '05-01-2024', '06-01-2024', '07-01-2024', '08-01-2024', '09-01-2024', '10-01-2024']
}

# Create DataFrame
df = pd.DataFrame(data)

In [2]:
df.head()

   Order_ID  Region      Category  Sales  Quantity  Profit  Order_Date
0      1001    north  Electronics  $1200       5.0     200  01-01-2024
1      1002    South  electronics   $850       3.0     120  02-01-2024
2      1003     EAST    Furniture  $2500       2.0     400  03-01-2024
3      1004     west     furnture  $1750       1.0     250  04-01-2024
4      1005    North  Electronics  $1200       5.0     200  01-01-2024

In [3]:
df.shape

(12, 7)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    12 non-null     int64
 1    Region     12 non-null     object
 2   Category    12 non-null     object
 3   Sales       11 non-null     object
 4   Quantity    11 non-null     float64
 5   Profit      12 non-null     int64
 6   Order_Date  12 non-null     object
dtypes: float64(1), int64(2), object(4)
memory usage: 804.0+ bytes

In [7]:
df.isnull().sum()[df.isnull().sum()>0]

Sales       1
Quantity    1
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(1)

In [9]:
df.columns=df.columns.str.strip().str.lower()
df.head()

   order_id region     category  sales  quantity  profit  order_date
0      1001  north  Electronics  $1200       5.0     200  01-01-2024
1      1002  South  electronics   $850       3.0     120  02-01-2024
2      1003   EAST    Furniture  $2500       2.0     400  03-01-2024
3      1004   west     furnture  $1750       1.0     250  04-01-2024
4      1005  North  Electronics  $1200       5.0     200  01-01-2024

In [15]:
df.drop_duplicates(inplace= True)

In [16]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
6     False
7     False
8     False
9     False
10    False
11    False
dtype: bool

In [17]:
df['region']=df['region'].str.title()
df['category']=df['category'].str.title()

df['category']=df['category'].replace("Furnture","Furniture")

df.head()

   order_id region     category  sales  quantity  profit  order_date
0      1001  North  Electronics  $1200       5.0     200  01-01-2024
1      1002  South  Electronics   $850       3.0     120  02-01-2024
2      1003   East    Furniture  $2500       2.0     400  03-01-2024
3      1004   West    Furniture  $1750       1.0     250  04-01-2024
4      1005  North  Electronics  $1200       5.0     200  01-01-2024

In [21]:
df['sales']=df['sales'].str.replace('$','',regex=False)
df['sales']=df['sales'].astype(float)

df['sales']=df['sales'].fillna(df['sales'].mean())

df.head()

   order_id region     category   sales  quantity  profit  order_date
0      1001  North  Electronics  1200.0       5.0     200  01-01-2024
1      1002  South  Electronics   850.0       3.0     120  02-01-2024
2      1003   East    Furniture  2500.0       2.0     400  03-01-2024
3      1004   West    Furniture  1750.0       1.0     250  04-01-2024
4      1005  North  Electronics  1200.0       5.0     200  01-01-2024

In [23]:
df['quantity']=df['quantity'].fillna(df['quantity'].mean())
df.head()

   order_id region     category   sales  quantity  profit  order_date
0      1001  North  Electronics  1200.0       5.0     200  01-01-2024
1      1002  South  Electronics   850.0       3.0     120  02-01-2024
2      1003   East    Furniture  2500.0       2.0     400  03-01-2024
3      1004   West    Furniture  1750.0       1.0     250  04-01-2024
4      1005  North  Electronics  1200.0       5.0     200  01-01-2024

In [24]:
df

    order_id region         category   sales  quantity  profit  order_date
0       1001  North      Electronics  1200.0       5.0     200  01-01-2024
1       1002  South      Electronics   850.0       3.0     120  02-01-2024
2       1003   East        Furniture  2500.0       2.0     400  03-01-2024
3       1004   West        Furniture  1750.0       1.0     250  04-01-2024
4       1005  North      Electronics  1200.0       5.0     200  01-01-2024
6       1006  South  Office Supplies   300.0       7.0      50  05-01-2024
7       1007   East  Office Supplies   450.0       4.0      60  06-01-2024
8       1008   West      Electronics  1100.0       6.0     180  07-01-2024
9       1009  North        Furniture  1160.0       2.0      90  08-01-2024
10      1010  South      Electronics   950.0       3.9     150  09-01-2024
11      1011   East      Electronics  1300.0       4.0     220  10-01-2024

In [25]:
df['quantity']=df['quantity'].astype(int)
df.head()

   order_id region     category   sales  quantity  profit  order_date
0      1001  North  Electronics  1200.0         5     200  01-01-2024
1      1002  South  Electronics   850.0         3     120  02-01-2024
2      1003   East    Furniture  2500.0         2     400  03-01-2024
3      1004   West    Furniture  1750.0         1     250  04-01-2024
4      1005  North  Electronics  1200.0         5     200  01-01-2024

In [26]:
df['profit']=df['profit'].astype(float)
df.head()

   order_id region     category   sales  quantity  profit  order_date
0      1001  North  Electronics  1200.0         5   200.0  01-01-2024
1      1002  South  Electronics   850.0         3   120.0  02-01-2024
2      1003   East    Furniture  2500.0         2   400.0  03-01-2024
3      1004   West    Furniture  1750.0         1   250.0  04-01-2024
4      1005  North  Electronics  1200.0         5   200.0  01-01-2024

In [27]:
df['order_date']=pd.to_datetime(df['order_date'],format='%d-%m-%Y')
df.head()

   order_id region     category   sales  quantity  profit order_date
0      1001  North  Electronics  1200.0         5   200.0 2024-01-01
1      1002  South  Electronics   850.0         3   120.0 2024-01-02
2      1003   East    Furniture  2500.0         2   400.0 2024-01-03
3      1004   West    Furniture  1750.0         1   250.0 2024-01-04
4      1005  North  Electronics  1200.0         5   200.0 2024-01-01

In [28]:
higer_sale=df[df['sales']>1000]

higer_sale

    order_id region     category   sales  quantity  profit order_date
0       1001  North  Electronics  1200.0         5   200.0 2024-01-01
2       1003   East    Furniture  2500.0         2   400.0 2024-01-03
3       1004   West    Furniture  1750.0         1   250.0 2024-01-04
4       1005  North  Electronics  1200.0         5   200.0 2024-01-01
8       1008   West  Electronics  1100.0         6   180.0 2024-01-07
9       1009  North    Furniture  1160.0         2    90.0 2024-01-08
11      1011   East  Electronics  1300.0         4   220.0 2024-01-10

In [30]:
total_Sales=df.groupby('region').agg(
    Total_Sales_region=('sales','sum')
)

total_Sales

        Total_Sales_region
region
East                4250.0
North               3560.0
South               2100.0
West                2850.0

In [33]:
total_profit=df.groupby('category').agg(
    Total_profit_category =('profit','sum')
)

total_profit

                 Total_profit_category
category
Electronics                     1070.0
Furniture                        740.0
Office Supplies                  110.0

In [37]:
sales_arry=df['sales'].to_numpy()

sales_arry

array([1320.,  935., 2750., 1925., 1320.,  330.,  495., 1210., 1276.,
       1045., 1430.])

In [38]:
sales_arry=sales_arry *1.10

sales_arry[:5]

array([1452. , 1028.5, 3025. , 2117.5, 1452. ])