<a href="https://colab.research.google.com/github/MohammedShahad7/Data-Science-/blob/main/Tidy%20Data%20Principles%20for%20EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import seaborn as sns

df = sns.load_dataset('titanic')

print("Dataset loaded successfully!")
print(f"Shape: {df.shape}")
df.head()

Dataset loaded successfully!
Shape: (891, 15)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [ ]:
df.duplicated().sum()

np.int64(107)

In [ ]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [ ]:
df.shape

(891, 15)

In [ ]:
df['survived'].nunique()

2

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
wide_df = df.pivot_table(
    values='fare',
    index='pclass',
    columns='sex',
    aggfunc='mean'
).reset_index()

print(wide_df)

sex  pclass      female       male
0         1  106.125798  67.226127
1         2   21.970121  19.741782
2         3   16.118810  12.661633

In [ ]:
len_df=pd.melt(
    wide_df,
    id_vars='pclass',
    value_vars=['female', 'male'],
    var_name='Sex',
    value_name='Fare'
)

len_df

   pclass     Sex        Fare
0       1  female  106.125798
1       2  female   21.970121
2       3  female   16.118810
3       1    male   67.226127
4       2    male   19.741782
5       3    male   12.661633

In [ ]:
df['deck'].value_counts(dropna=False)

deck
NaN    688
C       59
B       47
D       33
E       32
A       15
F       13
G        4
Name: count, dtype: int64

In [ ]:
df['deck'].isnull().sum()

np.int64(688)

In [ ]:
print(df['embarked'].unique())
df['embarked'] = df['embarked'].str.strip().str.upper()

['S' 'C' 'Q' nan]

In [ ]:
print(df['embarked'].unique())

['S' 'C' 'Q' nan]

In [ ]:
print(df['sex'].unique())

['male' 'female']

In [ ]:
df['sex'] = df['sex'].str.strip().str.lower()

In [ ]:
print(df['sex'].unique())

['male' 'female']

# Subtask 4: Tidy Violation Summary

### 1. Which of the three tidy data rules did the Titanic dataset violate?

The Titanic dataset does **not have a major violation of the three tidy data rules**.

* **Rule 1: Each variable forms exactly one column.**
  The dataset mostly satisfies this rule because variables such as `age`, `sex`, `fare`, `embarked`, `deck`, and `survived` have their own columns.

* **Rule 2: Each observation forms exactly one row.**
  The dataset satisfies this rule because each row represents information about **one passenger**.

* **Rule 3: Each type of observational unit forms exactly one table.**
  The dataset satisfies this rule because the table describes one main observational unit: **passengers**.

Therefore, **no specific column clearly violates the three core tidy-data rules in this version of the Titanic dataset**.

### 2. Which rules did it satisfy cleanly?

The dataset satisfies all three tidy data rules:

1. **One variable per column** – variables are stored in separate columns.
2. **One observation per row** – each row represents one passenger.
3. **One type of observational unit per table** – the table contains passenger-level information.

The dataset may still contain missing values and other data-quality issues, but missing values do not automatically mean that the data is not tidy.

### 3. One data quality issue that today's operations cannot fix

One important data-quality issue is the **missing values**, especially in the `age` and `deck` columns.

The operations used today can **identify** missing values using:

```python
df.isnull().sum()
```

but they cannot decide what the missing value should actually be.

To fix this, we need a **data-imputation or domain-based decision**. For example, missing `age` values could be replaced using the median age or another suitable statistical method. Missing `deck` values could potentially be left as missing if there is no reliable information available.

This requires a decision based on the meaning of the data, not just a simple cleaning operation.